version: "3.2"

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest
    platform: linux/amd64
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "PASSword123!"
      ACCEPT_EULA: "Y"
    networks:
      - external_network

networks:
  external_network:
    external: true